#국토교통부 지하철정보서비스

##키워드기반 지하철역 목록 조회

In [ ]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
from xml.etree import ElementTree
import pandas as pd

skey = 'crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D'

url = 'http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getKwrdFndSubwaySttnList'
params = '?' + 'ServiceKey=' + skey + '&' + \
          urlencode({quote_plus('subwayStationName') : '서울'})
print(url + params)

request = Request(url + params)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()
#print(response_body)

root = ElementTree.fromstring(response_body)

df = pd.DataFrame()
for item in root.iter('item'):
  item_dict = {}
  item_dict['subwayRouteName'] = item.find('subwayRouteName').text
  item_dict['subwayStationId'] = item.find('subwayStationId').text
  item_dict['subwayStationName'] = item.find('subwayStationName').text
  df = df.append(item_dict, ignore_index=True)

df

http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getKwrdFndSubwaySttnList?ServiceKey=crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D&subwayStationName=%EC%84%9C%EC%9A%B8

  subwayRouteName subwayStationId subwayStationName
0          서울 1호선          SUB133               서울역
1             분당선         SUB1511               서울숲
2            공항철도         SUB4001               서울역
3           경의중앙선         SUB1610               서울역
4          서울 2호선          SUB228             서울대입구
5          서울 4호선          SUB426               서울역
6          서울 6호선          SUB647        봉화산(서울의료원)

##지하철역 출구별 버스노선 목록 조회

In [ ]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
from xml.etree import ElementTree
import pandas as pd

skey = 'crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D'

url = 'http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getSubwaySttnExitAcctoBusRouteList'
params = '?' + 'ServiceKey=' + skey + '&' + \
          urlencode({quote_plus('subwayStationId') : 'SUB228'})
print(url + params)

request = Request(url + params)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()
#print(response_body)

root = ElementTree.fromstring(response_body)

df = pd.DataFrame()
for item in root.iter('item'):
  item_dict = {}
  item_dict['busRouteNo'] = item.find('busRouteNo').text
  item_dict['exitNo'] = item.find('exitNo').text
  df = df.append(item_dict, ignore_index=True)

df

http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getSubwaySttnExitAcctoBusRouteList?ServiceKey=crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D&subwayStationId=SUB228

   busRouteNo exitNo
0         461      1
1        5413      1
2        5524      1
3        5528      1
4        5530      1
5         641      1
6         643      1
7         650      1
8        6515      1
9  8541(맞춤버스)      1

##지하철역 출구별 주변 시설 목록 조회

In [ ]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
from xml.etree import ElementTree
import pandas as pd

skey = 'crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D'

url = 'http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getSubwaySttnExitAcctoCfrFcltyList'
params = '?' + 'ServiceKey=' + skey + '&' + \
          urlencode({quote_plus('subwayStationId') : 'SUB228'})
print(url + params)

request = Request(url + params)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()
#print(response_body)

root = ElementTree.fromstring(response_body)

df = pd.DataFrame()
for item in root.iter('item'):
  item_dict = {}
  item_dict['dirDesc'] = item.find('dirDesc').text
  item_dict['exitNo'] = item.find('exitNo').text
  df = df.append(item_dict, ignore_index=True)

df

http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getSubwaySttnExitAcctoCfrFcltyList?ServiceKey=crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D&subwayStationId=SUB228

       dirDesc exitNo
0        사랑의병원      1
1    아웃백,미스터피자      1
2         하나은행      1
3          KFC      2
4     국민은행, 농협      2
5      굿모닝신한증권      2
6       대우슈페리움      2
7     디오슈페리어빌딩      2
8        서울법학원      2
9  건영아파트,삼성아파트      3

##지하철역별 시간표 목록 조회

In [ ]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
from xml.etree import ElementTree
import pandas as pd

skey = 'crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D'

url = 'http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getSubwaySttnAcctoSchdulList'
params = '?' + 'ServiceKey=' + skey + '&' + \
          urlencode({quote_plus('subwayStationId') : 'SUB228', quote_plus('dailyTypeCode') : '03',
                     quote_plus('upDownTypeCode') : 'U'})
print(url + params)

request = Request(url + params)
request.get_method = lambda: 'GET'
response_body = urlopen(request).read()
#print(response_body)

root = ElementTree.fromstring(response_body)

df = pd.DataFrame()
for item in root.iter('item'):
  item_dict = {}
  item_dict['arrTime'] = item.find('arrTime').text
  item_dict['dailyTypeCode'] = item.find('dailyTypeCode').text
  item_dict['depTime'] = item.find('depTime').text
  item_dict['endSubwayStationId'] = item.find('endSubwayStationId').text
  item_dict['endSubwayStationNm'] = item.find('endSubwayStationNm').text
  item_dict['subwayRouteId'] = item.find('subwayRouteId').text
  item_dict['subwayStationId'] = item.find('subwayStationId').text
  item_dict['subwayStationNm'] = item.find('subwayStationNm').text
  item_dict['upDownTypeCode'] = item.find('upDownTypeCode').text
  df = df.append(item_dict, ignore_index=True)

df

http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getSubwaySttnAcctoSchdulList?ServiceKey=crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D&subwayStationId=SUB228&dailyTypeCode=03&upDownTypeCode=U

  arrTime dailyTypeCode depTime  ... subwayStationId subwayStationNm upDownTypeCode
0  000000            03  053000  ...          SUB228           서울대입구              U
1  054230            03  054300  ...          SUB228           서울대입구              U
2  054930            03  055000  ...          SUB228           서울대입구              U
3  055400            03  055430  ...          SUB228           서울대입구              U
4  060130            03  060200  ...          SUB228           서울대입구              U
5  060530            03  060600  ...          SUB228           서울대입구              U
6  061330            03  061400  ...          SUB228           서울대입구              U
7  062130            03  062200  ...          SUB228           서울대입구              U
8  062900            03  062930  ...          SUB228           서울대입구              U
9  063330            03  063400  ...          SUB228           서울대입구              U

[10 rows x 9 columns]

#지하철역별 시간표 목록 & 지하철역 출구별 시설 목록 조회 프로그램

In [ ]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
from xml.etree import ElementTree
import pandas as pd

select = int(input("1번: 지하철역별 시간표 목록 조회 / 2번: 지하철역 출구별 시설 목록 조회 : "))

if select == 1:

  subway_station_id = str(input("지하철역ID(ex SUB228): "))
  daily_type_code = str(input("요일 구분코드(01:평일, 02:토요일, 03:일요일): "))
  up_down_type_code = str(input("상하행 구분코드(U:상행, D:하행): "))

  skey = 'crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D'

  url = 'http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getSubwaySttnAcctoSchdulList'
  params = '?' + 'ServiceKey=' + skey + '&' + \
            urlencode({quote_plus('subwayStationId') : subway_station_id, quote_plus('dailyTypeCode') : daily_type_code,
                      quote_plus('upDownTypeCode') : up_down_type_code})
  #print(url + params)

  request = Request(url + params)
  request.get_method = lambda: 'GET'
  response_body = urlopen(request).read()

  root = ElementTree.fromstring(response_body)

  df = pd.DataFrame()
  for item in root.iter('item'):
    item_dict = {}
    item_dict['arrTime'] = item.find('arrTime').text
    item_dict['dailyTypeCode'] = item.find('dailyTypeCode').text
    item_dict['depTime'] = item.find('depTime').text
    item_dict['endSubwayStationId'] = item.find('endSubwayStationId').text
    item_dict['endSubwayStationNm'] = item.find('endSubwayStationNm').text
    item_dict['subwayRouteId'] = item.find('subwayRouteId').text
    item_dict['subwayStationId'] = item.find('subwayStationId').text
    item_dict['subwayStationNm'] = item.find('subwayStationNm').text
    item_dict['upDownTypeCode'] = item.find('upDownTypeCode').text
    df = df.append(item_dict, ignore_index=True)

  print(df)

else:
  subway_station_id = str(input("지하철역ID(ex SUB228): "))

  skey = 'crc%2FlWi6vrE%2BSqINyCZza2oF2mn0YET3A1EV5Rl3OION0X71d0C8BMhrhL0PkJMESoz61l246P4M8k%2BJyzOotw%3D%3D'

  url = 'http://openapi.tago.go.kr/openapi/service/SubwayInfoService/getSubwaySttnExitAcctoCfrFcltyList'
  params = '?' + 'ServiceKey=' + skey + '&' + \
            urlencode({quote_plus('subwayStationId') : subway_station_id})
  #print(url + params)

  request = Request(url + params)
  request.get_method = lambda: 'GET'
  response_body = urlopen(request).read()

  root = ElementTree.fromstring(response_body)

  df = pd.DataFrame()
  for item in root.iter('item'):
    item_dict = {}
    item_dict['dirDesc'] = item.find('dirDesc').text
    item_dict['exitNo'] = item.find('exitNo').text
    df = df.append(item_dict, ignore_index=True)

  print(df)

1번: 지하철역별 시간표 목록 조회 / 2번: 지하철역 출구별 시설 목록 조회 : 1
지하철역ID(ex SUB228): SUB228
요일 구분코드(01:평일, 02:토요일, 03:일요일): 01
상하행 구분코드(U:상행, D:하행): U
  arrTime dailyTypeCode depTime  ... subwayStationId subwayStationNm upDownTypeCode
0  000000            01  053000  ...          SUB228           서울대입구              U
1  054230            01  054300  ...          SUB228           서울대입구              U
2  054830            01  054900  ...          SUB228           서울대입구              U
3  055430            01  055500  ...          SUB228           서울대입구              U
4  060030            01  060100  ...          SUB228           서울대입구              U
5  060600            01  060630  ...          SUB228           서울대입구              U
6  061130            01  061200  ...          SUB228           서울대입구              U
7  061630            01  061700  ...          SUB228           서울대입구              U
8  062200            01  062230  ...          SUB228           서울대입구              U
9  062630            01  062700  ...          SUB228           서울대입구              U

[10 rows x 9 columns]