# BeautifulSoup 음악 순위 스크래핑

* 네이버 뮤직: https://music.naver.com/listen/top100.nhn

In [ ]:
from bs4 import BeautifulSoup
import urllib.request
import pandas as pd


def get_music_ranks(url):
  search_url = urllib.request.urlopen(url).read()
  soup = BeautifulSoup(search_url, 'html.parser')

  soup_titles = soup.select('a._title span.ellipsis')
  titles = [title.get_text() for title in soup_titles]
  soup_artist = soup.select('td._artist.artist > a')
  artists = [artist.get_text().strip() for artist in soup_artist] #strip(): 개인문자 제거
  #print(len(titles), len(artists))

  return titles, artists


url_p1 = "https://music.naver.com/listen/top100.nhn?domain=TOTAL_V2&page=1"
titles_50, artists_50 = get_music_ranks(url_p1)

url_p2 = "https://music.naver.com/listen/top100.nhn?domain=TOTAL_V2&page=2"
titles_100, artists_100 = get_music_ranks(url_p2)

ranks = [rank for rank in range(1, 101)]
rank_df = pd.DataFrame({"Rank": ranks,
                        "Title": titles_50 + titles_100,
                        "Artist": artists_50 + artists_100})

rank_df

    Rank                         Title              Artist
0      1                      Dynamite               방탄소년단
1      2                     다시 여기 바닷가  싹쓰리(유두래곤, 린다G, 비룡)
2      3                   마리아 (Maria)          화사(Hwa Sa)
3      4  When We Disco (Duet with 선미)                 박진영
4      5             How You Like That           BLACKPINK
..   ...                           ...                 ...
95    96     다시 여기 바닷가 (Acoustic Ver.)                 이상순
96    97                        그 여름 밤                   린
97    98           Error (Feat. Loopy)          ASH ISLAND
98    99                         Happy        태연 (TAEYEON)
99   100                       내 눈물 모아         휘인(Whee In)

[100 rows x 3 columns]